from enum import Enum


class TokenType(Enum):
    CONDITIONAL = "CONDITIONAL"
    OPERATOR = "OPERATOR"
    INDENTATION = "INDENTATION"
    RELOP = "RELOP"
    LOOP = "LOOP"
    IDENTIFIER = "IDENTIFIER"
    CONSTANT = "CONSTANT"
    FUNCTION = "FUNCTION"
    SYMBOL = "SYMBOL"
    SEMICOLON = "SEMICOLON"
    BLOCK_BEGIN = "BLOCK BEGIN"
    BLOCK_END = "BLOCK END"
    NEWLINE = "NEWLINE"
    EOF = "EOF"